array.exe : utils.o array.o main.o
	gcc utils.o array.o main.o -o array.exe

utils.o :
	gcc -c utils.c

array.o :
	gcc -c array.c

main.o :
	gcc -c main.c

clean :
	rm -f utils.o array.o main.o array.exe